platform: linux


image_resource:
  type: docker-image
  source:  
    repository: eboraas/laravel
  
inputs:
- name: project-repository
  path: project-repository
- name: pipeline-repository
  path: pipeline-repository

run:
  path: ls 
